services:
  - name: naming-server
    type: web
    env: docker
    plan: free
    dockerfilePath: naming-server/Dockerfile
    buildCommand: ""
    startCommand: ""
    ports:
      - 8761
    healthCheckPath: "/actuator/health"

  - name: currency-exchange
    type: web
    env: docker
    plan: free
    dockerfilePath: currency-exchange-service/Dockerfile
    buildCommand: ""
    startCommand: ""
    ports:
      - 8000
    envVars:
      - key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
        value: "http://naming-server:8761/eureka"
    healthCheckPath: "/actuator/health"
    dependsOn:
      - naming-server

  - name: currency-conversion
    type: web
    env: docker
    plan: free
    dockerfilePath: currency-conversion-service/Dockerfile
    buildCommand: ""
    startCommand: ""
    ports:
      - 8100
    envVars:
      - key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
        value: "http://naming-server:8761/eureka"
    healthCheckPath: "/actuator/health"
    dependsOn:
      - naming-server

  - name: api-gateway
    type: web
    env: docker
    plan: free
    dockerfilePath: api-gateway/Dockerfile
    buildCommand: ""
    startCommand: ""
    ports:
      - 8765
    envVars:
      - key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
        value: "http://naming-server:8761/eureka"
    healthCheckPath: "/actuator/health"
    dependsOn:
      - naming-server
